import express from 'express';
import multer from 'multer';
import { deleteAccount, deleteMember, getAccountById, getAccounts, getMembers, patchAccount, patchMember, postAccountSelf, postMember } from '../controllers/accounts.controller.ts';
import { getAccountLibrary, patchAccountLibraryFavorite, postAccountLibraryAsset, postAccountLibraryClone, postAccountLibraryEntry, postAccountLibraryImageUpload, postAccountLibraryUpload } from '../controllers/library.controller.ts';
import { getAccountEvents, postAccountEvent } from '../controllers/events.controller.ts';
import { requireActive } from '../middlewares/require-active.ts';
import { requireAuth } from '../middlewares/require-auth.ts';

const router = express.Router();
const uploadImage = multer({ storage: multer.memoryStorage(), limits: { fileSize: 25 * 1024 * 1024, files: 1 } });
router.use(requireAuth, requireActive);
router.get('/', getAccounts);
router.post('/', postAccountSelf);
router.get('/:accountId', getAccountById);
router.patch('/:accountId', patchAccount);
router.delete('/:accountId', deleteAccount);
router.get('/:accountId/events', getAccountEvents);
router.post('/:accountId/events', postAccountEvent);
router.get('/:accountId/library', getAccountLibrary);
router.post('/:accountId/library/uploads', postAccountLibraryUpload);
router.post('/:accountId/library/image-upload', uploadImage.single('file'), postAccountLibraryImageUpload);
router.post('/:accountId/library/assets', postAccountLibraryAsset);
router.post('/:accountId/library', postAccountLibraryEntry);
router.post('/:accountId/library/:libraryAssetId/clone', postAccountLibraryClone);
router.patch('/:accountId/library/:libraryAssetId/favorite', patchAccountLibraryFavorite);
router.get('/:accountId/members', getMembers);
router.post('/:accountId/members', postMember);
router.patch('/:accountId/members/:membershipId', patchMember);
router.delete('/:accountId/members/:membershipId', deleteMember);
export default router;
