import express from 'express';
import multer from 'multer';
import { deleteAccount, getAccountById, getAccounts, getMembers, patchAccount, postAccountSelf } from '../controllers/accounts.controller.ts';
import { getAccountLibrary, getAccountPhotoLayoutTemplate, getAccountPrintProfile, patchAccountLibraryFavorite, postAccountLibraryAsset, postAccountLibraryClone, postAccountLibraryEntry, postAccountLibraryImageUpload, postAccountLibraryUpload, postAccountPhotoLayoutTemplate, postAccountPrintProfile } from '../controllers/library.controller.ts';
import { getAccountEvents, postAccountEvent } from '../controllers/events.controller.ts';
import { requireActive } from '../middlewares/require-active.ts';
import { requireAuth } from '../middlewares/require-auth.ts';

const router = express.Router();
const uploadImage = multer({ storage: multer.memoryStorage(), limits: { fileSize: 25 * 1024 * 1024, files: 1 } });
router.use(requireAuth, requireActive);
router.get('/', getAccounts);
router.post('/', postAccountSelf);
router.get('/:accountId', getAccountById);
router.patch('/:accountId', patchAccount);
router.delete('/:accountId', deleteAccount);
router.get('/:accountId/events', getAccountEvents);
router.post('/:accountId/events', postAccountEvent);
router.get('/:accountId/library', getAccountLibrary);
router.post('/:accountId/library/uploads', postAccountLibraryUpload);
router.post('/:accountId/library/image-upload', uploadImage.single('file'), postAccountLibraryImageUpload);
router.post('/:accountId/library/assets', postAccountLibraryAsset);
router.post('/:accountId/library/layout-templates', postAccountPhotoLayoutTemplate);
router.get('/:accountId/library/:libraryAssetId/layout-template', getAccountPhotoLayoutTemplate);
router.post('/:accountId/library/print-profiles', postAccountPrintProfile);
router.get('/:accountId/library/:libraryAssetId/print-profile', getAccountPrintProfile);
router.post('/:accountId/library', postAccountLibraryEntry);
router.post('/:accountId/library/:libraryAssetId/clone', postAccountLibraryClone);
router.patch('/:accountId/library/:libraryAssetId/favorite', patchAccountLibraryFavorite);
router.get('/:accountId/members', getMembers);
router.all('/:accountId/members', (req, res, next) => req.method === 'GET' ? next() : res.status(410).json({ code: 'ACCOUNT_MEMBERS_RETIRED', error: 'Asigna miembros desde el evento' }));
router.all('/:accountId/members/:membershipId', (_req, res) => res.status(410).json({ code: 'ACCOUNT_MEMBERS_RETIRED', error: 'Asigna miembros desde el evento' }));
export default router;
