import express from 'express';
import { deleteEvent, deleteResource, getEvent, getModes, getResources, getTypes, patchEvent, patchEventBranding, patchResource, postResource } from '../controllers/events.controller.ts';
import { requireActive } from '../middlewares/require-active.ts';
import { requireAuth } from '../middlewares/require-auth.ts';
import { getActiveSession, getConfig, getPublished, getSessionPackage, patchSession, postApplyLayoutTemplate, postEndSession, postForceEndSession, postPublish, postSession, postValidate, putConfig } from '../controllers/magic-mirror.controller.ts';
import { getSessionSummary, patchRun, postAsset, postCapture, postCompleteAsset, postCompleteCapture, postRun } from '../controllers/mirror-runtime.controller.ts';

const router = express.Router();
router.use(requireAuth, requireActive);

router.get('/types', getTypes);
router.get('/modes', getModes);
router.get('/:id/modes/:eventModeId/config', getConfig);
router.put('/:id/modes/:eventModeId/config', putConfig);
router.post('/:id/modes/:eventModeId/config/validate', postValidate);
router.post('/:id/modes/:eventModeId/config/publish', postPublish);
router.post('/:id/modes/:eventModeId/layout-templates/:assetId/apply', postApplyLayoutTemplate);
router.get('/:id/modes/:eventModeId/config/published', getPublished);
router.get('/:id/modes/:eventModeId/sessions/active', getActiveSession);
router.post('/:id/modes/:eventModeId/sessions', postSession);
router.patch('/:id/modes/:eventModeId/sessions/:sessionId', patchSession);
router.post('/:id/modes/:eventModeId/sessions/:sessionId/end', postEndSession);
router.post('/:id/modes/:eventModeId/sessions/:sessionId/force-end', postForceEndSession);
router.get('/:id/modes/:eventModeId/sessions/:sessionId/package', getSessionPackage);
router.get('/:id/modes/:eventModeId/sessions/:sessionId/summary', getSessionSummary);
router.post('/:id/modes/:eventModeId/sessions/:sessionId/runs', postRun);
router.patch('/:id/modes/:eventModeId/sessions/:sessionId/runs/:runId', patchRun);
router.post('/:id/modes/:eventModeId/sessions/:sessionId/runs/:runId/captures', postCapture);
router.post('/:id/modes/:eventModeId/sessions/:sessionId/runs/:runId/captures/:captureId/complete', postCompleteCapture);
router.post('/:id/modes/:eventModeId/sessions/:sessionId/runs/:runId/assets', postAsset);
router.post('/:id/modes/:eventModeId/sessions/:sessionId/runs/:runId/assets/:assetId/complete', postCompleteAsset);
router.get('/:id', getEvent);
router.patch('/:id', patchEvent);
router.delete('/:id', deleteEvent);
router.patch('/:id/branding', patchEventBranding);
router.get('/:id/resources', getResources);
router.post('/:id/resources', postResource);
router.patch('/:id/resources/:resourceId', patchResource);
router.delete('/:id/resources/:resourceId', deleteResource);

export default router;
